name: chatgpt_client
description: Access OpenAI ChatGPT Public API using Dart Language. Supports native Dart project and all Flutter target platforms (iOS, Android, Windows, Linux, Web)
version: 1.1.1
homepage: https://github.com/alfianlosari/chatgpt_api_dart

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  http: ^0.13.5
  fetch_client: ^1.0.0
  web_browser_detect: ^2.0.3

dev_dependencies:
  test: ^1.23.1